### ISSUE TITLE
GHC eventlog based stats todo list

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streamly-metrics#10]
Changes to GHC:

* [ ] Put the code under ifdef `LINUX_PERF_EVENT`
* [ ] Enable the code only when `+RTS -l` is specified
* [ ] Support multiple counters at the same time
* [ ] Add a precise allocation counter

Changes to parser:

* [ ] Print periodically e.g. every second instead of on each event
* [ ] Print after collecting `n` events
